version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "1991:1991"
    volumes:
      - ./backend:/api
    tty: true
    working_dir: /api
    environment:
      - TZ=Asia/Tokyo